# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.7.3/c2cciutils/schema.json

# Map GH branches to Dockerhub tags
version:
  branch_to_version_re:
    - from: master
      to: unstable

publish:
  docker:
    latest: true
    images:
      - name: camptocamp/swisstopo-light-basemap
    repository:
      github:
        versions: []
