---
name: Rebuild

# scheduled GH-actions will run on the default branch only, master
on:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - v2.0.0
          - v3.0.0

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{matrix.branch}}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-swisstopo-light-basemap'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: make pull
      - run: make build
      - run: make acceptance

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{matrix.branch}}
